name: Code checks

on:
    push:
        branches: [ master ]

jobs:
  run_tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: Install python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: Install requirements
        run: pip install -r requirements.txt
        - name: Run tests
        run: coverage run unit_tests.py
        - name: Tests report
        run: coverage report
